#!/usr/bin/env bash

source ./project

RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'

_script_name="$(basename -- "${BASH_SOURCE[0]}")"

_platform=$1
if [ "$_platform" = "" ]; then
    echo -e "${RED}[FATAL] Platform not specified as first argument${NOCOLOR}"
    echo -e "Usage: $_script_name <platform>"
    exit 1
fi

_build_mode=$(echo "$2" | tr '[:upper:]' '[:lower:]')
case "$_build_mode" in
    "")
        _build_mode=debug
        ;;
    
    "debug")
        ;;
    
    "release")
        ;;
    
    *)
        echo -e "${RED}[FATAL] Invalid build mode: '$_build_mode' must be one of 'debug' or 'release' (case insensitive) ${NOCOLOR}"
        exit 2
esac

PATH_REPO_ROOT="$(realpath "$(dirname -- "${BASH_SOURCE[0]}")")"
PATH_EXTENSIONS_OUTPUT="$PATH_REPO_ROOT/$PROJECT_NAME/extensions"
PATH_VENDORS="$PATH_REPO_ROOT/vendor"
PATH_GODOT_CPP="$PATH_VENDORS/godot-cpp"

#region Copy extensions .gdextension files into project

for extension_relative_path in extensions/* ; do
    extension_name=$(basename $extension_relative_path)
    extension_out_path=$PATH_EXTENSIONS_OUTPUT/$extension_name
    if ! [ -d $extension_out_path ] ; then
        echo "Creating output path for $extension_name: $extension_out_path"
        mkdir -p $extension_out_path
    fi

    echo "Copying *.gdextension(.uid) file(s) for $extension_name..."
    cp $extension_relative_path/*.gdextension* $extension_out_path
done

#endregion Copy extensions .gdextension files into project

#region Build godot-cpp

PREVIOUS_CWD=$(pwd)

cd $PATH_GODOT_CPP
scons -j12 platform=$_platform use_llvm=yes custom_api_file=../../extension_api.json $_scons_params

cd $PREVIOUS_CWD

#endregion Build godot-cpp

#region Build extensions (scons)

echo "Building repo located at $PATH_REPO_ROOT"

if [ "$_platform" != web ]; then
    _scons_params="$_scons_params bits=64"
fi

if ! scons -j12 use_llvm=yes debug_symbols=yes target=template_$_build_mode platform=$_platform $_scons_params ; then
    echo -e "${RED}[FATAL] Error compiling extensions"
    exit 1
fi

#endregion Build extensions (scons)

#region Check for linker errors

echo "Checking for linker errors..."

_LINKER_ISSUES=0

for filename in ./extensions/*/bin/* ; do
    echo -e "Checking ${filename}"
    case "$filename" in
        "*.wasm")
            ;;
        "*.so*")
            _LDD_OUTPUT=$(ldd -d -r $filename)

            if [ $? -ne 0 ] ; then
                echo -e "${RED}[FATAL] Failed to run ldd against ${filename} ${NOCOLOR}"
                _LINKER_ISSUES=1
            else
                _UNDEFINED_SYMBOLS=$(_tab=$'\t' ; grep 'undefined symbol:' <<< $_LDD_OUTPUT | sed "s/^/$_tab/" | sed "s/^$_tab$//")
                if [ -n "$_UNDEFINED_SYMBOLS" ] ; then
                    echo -e "${RED}[FATAL] Found undefined symbols in ${filename}: ${NOCOLOR}\n${_UNDEFINED_SYMBOLS}"
                    _LINKER_ISSUES=1
                fi
            fi
    esac
done

if [ $_LINKER_ISSUES -ne 0 ] ; then
    echo -e "${RED}[FATAL] Linker issues found, please look above this line for which binaries failed ${NOCOLOR}"
    exit 2
else
    echo "No linker errors found"
fi

#endregion Check for linker errors

echo -e "${GREEN}Build succeeded"
